### ISSUE TITLE
Complete, decomposed DFDs

### ISSUE THREAD

**Issue by lizzyz77** [F17MIS4173Team6/Rose-Oil-Company#1]
Josh, You're assigned this issue per the PPP. We'll review in Sunday's meeting.

**Comment by watkinska15** [comment]
Rough Draft Level 1 DFD Processes 6 & 7

![level1dfdprocess6](https://user-images.githubusercontent.com/31592528/31457575-288baac4-ae8b-11e7-92b1-fcd9e156fbed.png)

![level1dfdprocess7](https://user-images.githubusercontent.com/31592528/31457588-30922694-ae8b-11e7-9ae2-cf0a75964260.png)

**Comment by lizzyz77** [comment]
![level 1 dfd process 2](https://user-images.githubusercontent.com/31494063/31511466-d18231aa-af55-11e7-851f-3281e7d6a482.jpeg)
![level 1dfd process 5](https://user-images.githubusercontent.com/31494063/31511470-d32e9160-af55-11e7-8cac-4777be0bd8e0.jpeg)

**Comment by lizzyz77** [comment]
![level 0 dfd](https://user-images.githubusercontent.com/31494063/31511492-e141a3dc-af55-11e7-8138-78a8dbc6873f.jpeg)

**Comment by watkinska15** [comment]
Revised Rough Draft Level 1 DFD Processes 6&7

![level1dfdprocess6](https://user-images.githubusercontent.com/31592528/31512057-a81f7884-af57-11e7-935f-164bbca48b93.png)


![level1dfdprocess7](https://user-images.githubusercontent.com/31592528/31512058-a83e3918-af57-11e7-9b56-94f29273e944.png)

**Comment by Forlines1** [comment]
![roseoillevel1dfdprocess3](https://user-images.githubusercontent.com/31662099/31521376-4230d6ec-af77-11e7-9d82-90a4e04a2cfa.PNG)

**Comment by Forlines1** [comment]
![roseoillevel1dfdprocess4](https://user-images.githubusercontent.com/31662099/31521386-4d9c6c8a-af77-11e7-8a80-b8e46bd32131.PNG)

**Comment by watkinska15** [comment]
Revised Level 1 DFD Processes 6&7

![level1dfdprocess6](https://user-images.githubusercontent.com/31592528/31527737-4ed1a496-af9d-11e7-932e-79d0893c7c12.png)

![level1dfdprocess7](https://user-images.githubusercontent.com/31592528/31527738-4ee2e03a-af9d-11e7-93c2-185b481d3498.png)

**Comment by lizzyz77** [comment]
Thanks guys!!
