### ISSUE TITLE
Physical Entity-Relationship Diagram (ERD)

### ISSUE THREAD

**Issue by lizzyz77** [F17MIS4173Team6/Rose-Oil-Company#2]
Hi Kathryn - this one's yours per the PPP. I'll upload your rough draft for now, and we'll review in Sunday's meeting. 
![erd_1](https://user-images.githubusercontent.com/31494063/31020424-f7aa2a36-a500-11e7-804a-150f8f682e82.png)

**Comment by watkinska15** [comment]
Updated ERD

![erd3](https://user-images.githubusercontent.com/31592528/31457485-e9b9cd94-ae8a-11e7-85b2-f89e4999782b.png)

**Comment by watkinska15** [comment]
Revised ERD 

![roseoilcoerd](https://user-images.githubusercontent.com/31592528/31527709-298fd018-af9d-11e7-90ad-05fe91a6b787.png)

**Comment by lizzyz77** [comment]
Thanks Kathryn!!

**Comment by lizzyz77** [comment]
Revision 4 ERD: (Thanks Kathryn! )
![roseoilcompany_erd](https://user-images.githubusercontent.com/31494063/31667625-f9336a22-b31d-11e7-846e-c92fb3714a99.png)
