### ISSUE TITLE
Mock-ups – Forms and Reports-Prototypes from VB or html 

### ISSUE THREAD

**Issue by lizzyz77** [F17MIS4173Team6/Rose-Oil-Company#3]
Mock-ups – Forms and Reports-Prototypes
Sample Reports- same as mock-up reports but with data.

Currently assigned to Alvin in the PPP, awaiting his presence in GitHub.

**Comment by lizzyz77** [comment]
![client](https://user-images.githubusercontent.com/31494063/31585264-fc30db8e-b18c-11e7-91a6-1659ca1b544e.PNG)
![login](https://user-images.githubusercontent.com/31494063/31585265-fc412f2a-b18c-11e7-88eb-f26f8b2fc129.PNG)
![product](https://user-images.githubusercontent.com/31494063/31585266-fc50d074-b18c-11e7-9aa7-86db734304a9.PNG)
![register](https://user-images.githubusercontent.com/31494063/31585267-fc648fa6-b18c-11e7-9a78-4964e809aad3.PNG)
![report](https://user-images.githubusercontent.com/31494063/31585268-fc756722-b18c-11e7-9a3e-e7622971516a.PNG)
![sales](https://user-images.githubusercontent.com/31494063/31585269-fc86b4d2-b18c-11e7-9893-26410b7cacf5.PNG)
![salesportal](https://user-images.githubusercontent.com/31494063/31585270-fc955dde-b18c-11e7-8fc6-9e7405009e17.PNG)
![addeditclient](https://user-images.githubusercontent.com/31494063/31585271-fca74b16-b18c-11e7-901f-52e891315a9b.PNG)
![addeditproduct](https://user-images.githubusercontent.com/31494063/31585272-fcb67c12-b18c-11e7-8147-8f7c6fb1ead5.PNG)
![addeditsale](https://user-images.githubusercontent.com/31494063/31585273-fcc57f78-b18c-11e7-9640-13233da38f87.PNG)

**Comment by lizzyz77** [comment]
Thanks Alvin!!

**Comment by alvindavis25** [comment]
Uploading the updated mockups

**Comment by alvindavis25** [comment]
![addeditclient](https://user-images.githubusercontent.com/31663563/31638877-e78ad4ec-b2a3-11e7-98ce-d31a19d2e65c.PNG)
![addeditproduct](https://user-images.githubusercontent.com/31663563/31638881-ed23f60e-b2a3-11e7-9be2-65cc335f1f04.PNG)
![addeditsale](https://user-images.githubusercontent.com/31663563/31638885-f01a7054-b2a3-11e7-925c-279a1317401d.PNG)
![client](https://user-images.githubusercontent.com/31663563/31638887-f214d35e-b2a3-11e7-819f-65c09c0224ac.PNG)
![product](https://user-images.githubusercontent.com/31663563/31638889-f3c3a676-b2a3-11e7-976e-fd871e48c531.PNG)
![report](https://user-images.githubusercontent.com/31663563/31638890-f5a2da52-b2a3-11e7-80e9-407da1d5eb31.PNG)
![sales](https://user-images.githubusercontent.com/31663563/31638893-f7333cc2-b2a3-11e7-9e73-4e0fefa06e87.PNG)

**Comment by alvindavis25** [comment]
here are all the correct mockups

![login](https://user-images.githubusercontent.com/31663563/31639164-5517e97c-b2a5-11e7-8e40-7cf3d43ecf07.PNG)
![register](https://user-images.githubusercontent.com/31663563/31639166-57ecb5c4-b2a5-11e7-8cbc-d4be399b15aa.PNG)
![salesportal](https://user-images.githubusercontent.com/31663563/31639169-5a846304-b2a5-11e7-9515-daa097f171ca.PNG)
![sales](https://user-images.githubusercontent.com/31663563/31639173-5e6a5e9c-b2a5-11e7-9c67-de92fa968259.PNG)
![addeditsale](https://user-images.githubusercontent.com/31663563/31639175-604a9704-b2a5-11e7-8c91-a95391f8f0d3.PNG)
![product](https://user-images.githubusercontent.com/31663563/31639180-644e9b02-b2a5-11e7-9d9d-39160cf63af4.PNG)
![addeditproduct](https://user-images.githubusercontent.com/31663563/31639181-6659c9e4-b2a5-11e7-97f6-8f4987ccde1f.PNG)
![client](https://user-images.githubusercontent.com/31663563/31639196-7da5224c-b2a5-11e7-8e9a-13746f4b7a29.PNG)
![addeditclient](https://user-images.githubusercontent.com/31663563/31639197-7f5b19b6-b2a5-11e7-8dc1-7d6c434d914d.PNG)
![report](https://user-images.githubusercontent.com/31663563/31639198-82061ce2-b2a5-11e7-9b10-e2501524491d.PNG)

**Comment by lizzyz77** [comment]
Great Mock-ups!! We still need a Report with Data.

**Comment by alvindavis25** [comment]
The Report Form has data in it. Is it blank for you?

**Comment by lizzyz77** [comment]
It only has report id, client id, etc... on the reports main menu. If I were to click on report id 2 (for example), a report should pull up with details (Salesman first and last name, date of the sale, product sold, etc...) This is the sample report we need.

Liz

________________________________

**Comment by alvindavis25** [comment]
Ok Im creating that functionality right now. So correct me if Im wrong, it needs the following:

Salesman First Name & Last Name
Date of Sale
Product ID/Product Sold
SaleID
ClientID
 Anything else?

**Comment by lizzyz77** [comment]
Take a look at the ERD:

[cid:f8bb7e2f-4d14-4d27-aa8d-ee29d5590323]


For a sample Report we need the following:
     Date (when the report was requested (so "today's date" for example) & the date the sale was made)

     ProductID (ProductType, Product Price, ProdDescription)

     ClientID (First/last name, PhoneNumber, Email, ClientType (residential or commercial), Address, City, State, Zip)

     SalesmanID (First/last name, email, HireDate)

Hope this makes sense. The report should show what is being sold, by who, to who, when, and how often....

Liz

________________________________

**Comment by alvindavis25** [comment]
Ok referencing the ERD now. Thank you for your patience with me on this part of our project. Will upload momentarily

**Comment by lizzyz77** [comment]
I think you're doing a really great job! I'm always here to help if you need too. Thank you all of your hard work. Don't forget to update your Time-sheet.

**Comment by alvindavis25** [comment]
Thank you and I wont forget. About to upload now

**Comment by alvindavis25** [comment]
![samplereport](https://user-images.githubusercontent.com/31663563/31672591-02cfcc3a-b32b-11e7-8a52-9e8f5de12e53.PNG)

**Comment by alvindavis25** [comment]
I nested the sample report in a messagebox for the time being. let me know if you need me to change anything. when you click on the report ID the messagebox opens a sample report

**Comment by lizzyz77** [comment]
Take a look at this sample report and let me know what you think: 

![image](https://user-images.githubusercontent.com/31494063/31675278-233fa43e-b332-11e7-855b-d2247d72b1ad.png)

**Comment by lizzyz77** [comment]
![image](https://user-images.githubusercontent.com/31494063/31676152-b898987c-b334-11e7-8afc-b032586634c0.png)

**Comment by alvindavis25** [comment]
It looks good to me. Im sorry I didn't know exactly what you were looking for so I thought the messagebox would suffice but clearly I was way off. That looks good to me other than the "Save" button. Why would we need to save a Report that is populated from the data already in the database? Print and Logout seem to be the only two buttons we need right?

**Comment by lizzyz77** [comment]
The Save button needs to send it to the President's email....

**Comment by alvindavis25** [comment]
ok works for me! we should use the form you created instead of me making one right now.

**Comment by lizzyz77** [comment]
Great, thanks!! I'll close this issue now. "See" you tonight!
