### ISSUE TITLE
Navigation Diagrams

### ISSUE THREAD

**Issue by lizzyz77** [F17MIS4173Team6/Rose-Oil-Company#4]
How will the user get around in the system?   
Another one for you Josh.

**Comment by Forlines1** [comment]
![roseoilnavdiagram](https://user-images.githubusercontent.com/31662099/31555531-61b7b178-b00f-11e7-8f21-d1f40791067b.PNG)

**Comment by Forlines1** [comment]
![roseoilnavdiagram](https://user-images.githubusercontent.com/31662099/31571722-27af60fa-b066-11e7-91ea-0c5eaa79b73f.PNG)

**Comment by lizzyz77** [comment]
Thanks Josh!!
