### ISSUE TITLE
Hardware and Software Specifications

### ISSUE THREAD

**Issue by lizzyz77** [F17MIS4173Team6/Rose-Oil-Company#5]
Remember, this is what the company uses currently and will use for access to our program. 

Assigned to Kathryn.

**Comment by watkinska15** [comment]
[RoseOilCo_HardwareSoftwareSpecifications.docx](https://github.com/F17MIS4173Team6/Rose-Oil-Company/files/1347658/RoseOilCo_HardwareSoftwareSpecifications.docx)

**Comment by watkinska15** [comment]
Updated Hardware and Software Specifications

[HardwareSoftwareSpecifications.docx](https://github.com/F17MIS4173Team6/Rose-Oil-Company/files/1367059/HardwareSoftwareSpecifications.docx)
